### ISSUE TITLE
Document Jasypt encryption processes

### ISSUE THREAD

**Issue by dixonwhitmire** [LinuxForHealth/docs#12]
@ccorley commented on [Wed Jul 08 2020](https://github.com/LinuxForHealth/connect/issues/49)

consider including guidance on using an env var for Jasypt master password, e.g. sysenv:CAMEL_ENCRYPTION_PASSWORD.

**Comment by ccorley** [comment]
Documented here: https://linuxforhealth.github.io/docs/develop/property-encryption.html
